### ISSUE TITLE
IDK how to use it !!

### ISSUE THREAD

**Issue by fonsua** [yRodrigo2219/lolapi#1]
I am new to this and would like to know how to open the file?

and what else to do to make it work.

sorry to bother

**Comment by yRodrigo2219** [comment]
What do you mean? This project is just a form of visualizing [this riot API](https://vickz84259.github.io/lolesports-api-docs/)
You don't really need to open anything, you can use the github-pages version [here](https://yrodrigo2219.github.io/lolapi/)

But, if you want to open it locally, you need yarn and nodejs installed.
